function init()
	msg.post('.', 'acquire_input_focus')
	local landing = gui.get_node("landing")
	gui.set_color(landing, vmath.vector4(0))
	gui.animate(landing, gui.PROP_COLOR, vmath.vector4(1, 1, 1, 1), gui.EASING_OUTEXPO, 0.5, 0)
end

function on_input(_, action_id, action)
	onTouch(action_id, action, {
		['play/button_bg'] = function()
			msg.post('main:/scenes#controller', 'change', { dest = 'options' })
			msg.post("#", "disable")
		end
	})
end
